from locust import HttpUser, between, task


class JsonPlaceholderUser(HttpUser):
    wait_time = between(0.5, 2.0)

    def _post_payload(self) -> dict[str, int | str]:
        return {
            "title": "Performance test post",
            "body": "Generated by Locust",
            "userId": 1,
        }

    @task(4)
    def list_posts(self) -> None:
        self.client.get("/posts", name="GET /posts")

    @task(4)
    def get_post(self) -> None:
        self.client.get("/posts/1", name="GET /posts/{id}")

    @task(2)
    def get_post_comments(self) -> None:
        self.client.get("/posts/1/comments", name="GET /posts/{id}/comments")

    @task(2)
    def get_comments_by_post_id(self) -> None:
        self.client.get("/comments?postId=1", name="GET /comments?postId={id}")

    @task(1)
    def create_post(self) -> None:
        with self.client.post(
            "/posts",
            json=self._post_payload(),
            name="POST /posts",
            catch_response=True,
        ) as response:
            if response.status_code != 201:
                response.failure(f"Expected 201, got {response.status_code}")

    @task(1)
    def replace_post(self) -> None:
        payload = self._post_payload() | {"id": 1}

        with self.client.put(
            "/posts/1",
            json=payload,
            name="PUT /posts/{id}",
            catch_response=True,
        ) as response:
            if response.status_code != 200:
                response.failure(f"Expected 200, got {response.status_code}")

    @task(1)
    def update_post(self) -> None:
        with self.client.patch(
            "/posts/1",
            json={"title": "Updated performance test post"},
            name="PATCH /posts/{id}",
            catch_response=True,
        ) as response:
            if response.status_code != 200:
                response.failure(f"Expected 200, got {response.status_code}")

    @task(1)
    def delete_post(self) -> None:
        with self.client.delete(
            "/posts/1",
            name="DELETE /posts/{id}",
            catch_response=True,
        ) as response:
            if response.status_code != 200:
                response.failure(f"Expected 200, got {response.status_code}")
